set encoding=utf-8
set number
set nowritebackup
set nobackup
set ambiwidth=double
set autoread
set cursorline
set cursorcolumn
set visualbell
syntax enable
set expandtab
set tabstop=2
set shiftwidth=2
set ignorecase
set smartcase
set incsearch
set wrapscan
set hlsearch
set tw=0
nmap <Esc><Esc> :nohlsearch<CR><Esc>
set list
set listchars=tab:>-,trail:.
