[tools]
bun = "latest"
deno = "latest"
node = "lts"
npm = "latest"
"npm:eslint" = "latest"
"npm:stylelint" = "latest"
"npm:tsx" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
oxfmt = "latest"
oxlint = "latest"
pnpm = "latest"
prettier = "latest"
yarn = "latest"
