name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lint
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/lint/lint.sh \
            koalaman/shellcheck-alpine

  test-on-alpine:
    name: Test on Alpine Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on alpine container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            alpine:latest

  test-on-archlinux:
    name: Test on Arch Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on archlinux container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            archlinux:latest

  test-on-debian:
    name: Test on Debian
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on debian container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            debian:latest

  test-on-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on ubuntu container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            ubuntu:latest
