name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lint
        run: |
          docker build --file ./dockerfiles/lint/Dockerfile --tag dotfiles-lint .
          docker run --rm dotfiles-lint

  test-on-alpine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on alpine container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            alpine:latest

  test-on-archlinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on archlinux container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            archlinux:latest

  test-on-debian:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on debian container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            debian:latest

  test-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: test on ubuntu container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/test.sh \
            ubuntu:latest
