name: Debian

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-on-debian:
    name: Test on Debian
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: test on debian container
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/test/install_test.sh \
            debian:latest
