name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  shfmt:
    name: Run shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shfmt
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/lint/shfmt.sh \
            mvdan/shfmt:latest-alpine

  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shellcheck
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/lint/shellcheck.sh \
            koalaman/shellcheck-alpine:latest
