name: macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-on-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: test on macOS
        run: ./install.sh
