name: shfmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup aqua
        uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.55.1

      - name: Run shfmt
        run: |
          shfmt --list --diff .
