name: shfmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Setup aqua
        uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
        with:
          aqua_version: v2.27.3

      - name: Run shfmt
        run: |
          shfmt --list --diff .
