name: shfmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shfmt:
    name: Run shfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: shfmt
        run: |
          docker run \
            --rm \
            --volume "$PWD":/root/.dotfiles:ro \
            --entrypoint /root/.dotfiles/lint/shfmt.sh \
            mvdan/shfmt:latest-alpine
