name: shfmt

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup aqua
        uses: aquaproj/aqua-installer@fd2089d1f56724d6456f24d58605e6964deae124 # v2.3.2
        with:
          aqua_version: v2.25.0

      - name: Run shfmt
        run: |
          # shellcheck disable=SC2046
          shfmt -i 2 -ci -d $(shfmt -f . | grep -v '\.zsh$')
