name: StyLua

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  luacheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup aqua
        uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
        with:
          aqua_version: v2.54.1

      - name: Run StyLua
        run: stylua --check .
